services:
  - type: web
    name: leave-tracker
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_APP_NAME
        value: Leave Tracker
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
    healthCheckPath: /
    autoDeploy: true
