services:
  - type: static
    name: leave-tracker
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_NAME
        value: Leave Tracker
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
